framework:
    messenger:
        default_bus: messenger.bus.command

        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.event.async: ~

            messenger.bus.query:
                default_middleware: false
                middleware:
                    - handle_message

        transports:
            events: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'App\Core\Message\Event\Event': events
