api-tenants:
    resource: '../../src/Module/*/Infrastructure/Rest/Controller/*'
    name_prefix: api_accounts_
    prefix: /api/accounts/{accountId}
    requirements:
        accountId: '\d+'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
