api-tenants:
    resource: '../../src/Module/*/Infrastructure/Rest/Controller/*'
    name_prefix: api_tenants
    prefix: /api/tenants/{tenantId}
    requirements:
        tenantId: '\d+'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
