services:
  App\Module\TodoList\Domain\TaskRepository:
    factory: '@App\Module\TodoList\Infrastructure\Persistence\InMemoryTaskRepositoryFactory'

  App\Module\TodoList\Application\Api\Controller\:
    resource: '../../src/Module/TodoList/Application/Api/Controller'
    tags: ['controller.service_arguments']
