services:
  App\Module\TodoList\Domain\TaskRepository:
    factory: ['@doctrine.orm.account_entity_manager', getRepository]
    arguments:
      - 'App\Module\TodoList\Infrastructure\Persistence\Doctrine\Entity\TaskDoctrine'
