
imports:
    - { resource: modules/**/services.yaml }
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Core\:
        resource: '../src/Core/*'
        exclude: '../src/Core/{Maker}'

    App\Core\Maker\:
        resource: '../src/Core/Maker/*'
        tags: ['maker.command']

    App\Module\:
        resource: '../src/Module/*'
        exclude: '../src/*/{Doctrine/Entity}'

