
imports:
    - { resource: modules/**/services.yaml }
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Core\:
        resource: '../src/Core/*'

    App\Core\Tenant\Doctrine\TenantConnectionContextService:
        arguments: ['@App\Core\Tenant\Doctrine\TenantConnectionParamsProvider', '@doctrine.orm.tenant_entity_manager']

    App\Module\:
        resource: '../src/Module/*'
        exclude: '../src/*/{Doctrine/Entity}'

