
imports:
    - { resource: modules/**/services.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Core\:
        resource: '../src/Core/*'

    App\Core\Account\Doctrine\DoctrineAccountContextService:
        arguments: ['@App\Core\Account\Doctrine\AccountConnectionParamsProvider', '@doctrine.orm.account_entity_manager']

    App\Module\:
        resource: '../src/Module/*'
        exclude: '../src/*/{Doctrine/Entity}'

    doctrine.dbal.connection_factory:
        class: App\Core\Doctrine\DoctrineConnectionFactory
        arguments: ['%doctrine.dbal.connection_factory.types%', '%kernel.project_dir%/config/modules']
