imports:
  - { resource: ./modules/**/services.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:

    App\Core\Message\Command\CommandHandler:
      public: true
      tags:
        - { name: messenger.message_handler, bus: messenger.bus.command }

    App\Core\Message\Event\EventHandler:
      public: true
      tags:
        - { name: messenger.message_handler, bus: messenger.bus.event.async }

    App\Core\Message\Query\QueryHandler:
      public: true
      tags:
        - { name: messenger.message_handler, bus: messenger.bus.query }

    App\Core\Rest\Controller\Controller:
      public: true
      tags: ['controller.service_arguments']


  App\Core\:
    resource: '../src/Core/*'

  App\Core\Account\Doctrine\DoctrineAccountContextService:
    arguments: ['@App\Core\Account\Doctrine\AccountConnectionParamsProvider', '@doctrine.orm.account_entity_manager']

  doctrine.dbal.connection_factory:
    class: App\Core\Doctrine\DoctrineConnectionFactory
    arguments: ['%doctrine.dbal.connection_factory.types%', '%kernel.project_dir%/config/modules']

  App\Core\Message\Command\CommandBus:
    arguments:
      - '@messenger.bus.command'

  App\Core\Message\Event\EventBus:
    arguments:
      - '@messenger.bus.event.async'

  App\Core\Message\Query\QueryBus:
    arguments:
      - '@messenger.bus.query'

  App\Module\:
    resource: '../src/Module/*'
    exclude: '../src/*/{Doctrine/Entity}'

